# Generated by Django 4.2 on 2023-06-15 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_usuario',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='InformeModificacionUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesional', models.CharField(max_length=20)),
                ('documento_profesional', models.CharField(max_length=20)),
                ('numero_caso_profesional', models.CharField(max_length=20)),
                ('fecha_informe', models.DateField()),
                ('accion_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.tipoaccion')),
                ('admin_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.admincontratacion')),
                ('especialidad_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.especialidad')),
                ('perfil_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.perfil')),
                ('prestador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.prestador')),
                ('regional_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informes.regional')),
            ],
        ),
    ]
